version: "3"
services:
  postgres:
    image: postgres
    ports: 
         - "5432:5432"
    environment: 
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "monstros"
    networks:
      - pgnet
    
  adminer:
    image: adminer
    ports: 
            - "8080:8080"
    depends_on: 
      - postgres
    networks:
      - pgnet


networks:
  pgnet: